# Generated by Django 3.1 on 2021-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(help_text='Enter your full name', max_length=250, verbose_name='full name')),
                ('email', models.EmailField(help_text='Enter your email address', max_length=255, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(help_text='Please enter your mobile number without any prefix e.g. 1234567890', max_length=10, unique=True, verbose_name='mobile number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
