# Generated by Django 3.1 on 2021-01-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=350)),
                ('prod_type', models.CharField(choices=[('clothing', 'Clothing'), ('bags', 'Bags & luggage'), ('footwear', 'Footwear'), ('electronics', 'Electronics'), ('beauty_grocery', 'Beauty & Grocery'), ('sports', 'Sports'), ('books', 'Books'), ('baby', 'Baby Products')], max_length=250)),
                ('prod_image', models.ImageField(blank=True, upload_to='product_images')),
                ('active', models.BooleanField(default=True)),
                ('prod_desc', models.TextField(max_length=1500)),
                ('prod_price', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
