# Generated by Django 3.1 on 2021-01-16 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_added',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 13, 23, 58, 375542)),
        ),
    ]
