# Generated by Django 3.1 on 2021-01-16 13:17

import datetime
from django.db import migrations, models
import mystoreapp.validation


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0004_auto_20210116_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(help_text='Please enter your mobile number without any prefix e.g. 1234567890', max_length=10, unique=True, validators=[mystoreapp.validation.validate_mobile], verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(help_text='Enter your full name', max_length=250, validators=[mystoreapp.validation.validate_name], verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 18, 47, 3, 118299)),
        ),
    ]
