# Generated by Django 3.1 on 2021-01-16 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0005_auto_20210116_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 19, 2, 35, 706096)),
        ),
    ]
