# Generated by Django 3.1 on 2021-01-17 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0007_auto_20210117_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(default='https://vcunited.club/wp-content/uploads/2020/01/No-image-available-2.jpg', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 17, 9, 27, 478493)),
        ),
    ]
