# Generated by Django 3.1 on 2021-01-17 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0008_auto_20210117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(default='/static/noimage.jpg', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 17, 16, 5, 715189)),
        ),
    ]
