# Generated by Django 3.1 on 2021-01-17 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0012_auto_20210117_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 22, 28, 21, 413101)),
        ),
    ]
