# Generated by Django 3.1 on 2021-01-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0017_auto_20210118_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
