# Generated by Django 3.1 on 2021-01-19 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0018_auto_20210119_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=350, unique=True)),
                ('prod_type', models.CharField(choices=[('clothing', 'Clothing'), ('bags', 'Bags & luggage'), ('footwear', 'Footwear'), ('electronics', 'Electronics'), ('beauty_grocery', 'Beauty & Grocery'), ('sports', 'Sports'), ('books', 'Books'), ('baby', 'Baby Products')], help_text='choose one from [clothing, bags, footwear, electronics, beauty_grocery, sports, books, baby]', max_length=250)),
                ('prod_image', models.ImageField(default='/static/images/noimage.jpg', upload_to='product_images/')),
                ('active', models.BooleanField(default=True)),
                ('prod_desc', models.TextField(max_length=1500)),
                ('prod_price', models.FloatField()),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 17, 0, 48, 27653))),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
